before_script:
    - export WD=`pwd`
    - export GOROOT="/opt/google/go-1.7.1"
    - export GOPATH="$WD/vendor:$WD"
    - export PATH="$GOROOT/bin:$PATH"

stages:
    - compile

goxc_build:
    stage: compile
    script:
        - mkdir -p bin
        - cd bin
        - go get github.com/fzipp/gocyclo
        - go build -installsuffix netgo -tags netgo -a -ldflags "-s -X main.version=${CI_BUILD_REF_NAME}-${CI_BUILD_ID}-`echo ${CI_BUILD_REF} | cut -c1-8` -X main.rev=${CI_BUILD_REF} -X main.built=`date -u +%Y%m%d-%H%M%S`" ../src/go/goxc
        - go test -cover -v ../src/go/goxc
        - go tool vet -all -v ../src/go/goxc
        - gocyclo -over 10 ../src/go/goxc
    artifacts:
        paths:
            - bin/goxc
        name: "goxc-${CI_BUILD_REF_NAME}-${CI_BUILD_ID}-`echo ${CI_BUILD_REF} | cut -c1-8`"
        expire_in: 1 week
        when: on_success
    except:
        - tags

goxc_release_build:
    stage: compile
    script:
        - mkdir -p bin
        - cd bin
        - go build -installsuffix netgo -tags netgo -a -ldflags "-s -X main.version=`echo \"${CI_BUILD_TAG}\" | sed -e 's/goxc-//'`-${CI_BUILD_ID} -X main.rev=${CI_BUILD_REF} -X main.built=`date -u +%Y%m%d-%H%M%S`" ../src/go/goxc
    artifacts:
        paths:
            - bin/goxc
        name: "${CI_BUILD_TAG}-${CI_BUILD_ID}"
        when: on_success
    only:
        - tags
        - /^goxc-*$/
