before_script:
    - export WD=`pwd`
    - export GOROOT="/opt/google/go-1.7.1"
    - export GOPATH="$WD/vendor:$WD"
    - export PATH="$GOROOT/bin:$PATH"

stages:
    - compile

goxc_build:
    stage: compile
    script:
        - mkdir -p bin
        - cd bin
        - go build -installsuffix netgo -tags netgo -a -ldflags "-s -X main.version=${CI_BUILD_TAG} -X main.rev=${CI_BUILD_REF} -X main.built=`date -u +%Y%m%d-%H%M%S`" ../src/go/goxc
    artifacts:
        paths:
            - bin/goxc
        name: "goxc-${CI_BUILD_REF}"
        expire_in: 1 week
        when: on_success
